### ISSUE TITLE
Use `ctv` package

### ISSUE THREAD

**Issue by barryrowlingson** [Robinlovelace/install-geocomp-ubuntu#1]
Why not use `ctv::install.views("Spatial")` to get all the packages referenced in the Spatial Task View? 

Win: No need to keep a list manually up to date here.
Win: Gets everything.

Lose: Currently it lists `length(ctv:::.get_pkgs_from_ctv_or_repos(views = "Spatial")[[1]])` = 168 packages. Some may have system requirements you need to satisfy first (eg Java, Python)

**Comment by Robinlovelace** [comment]
Yes that's a possibility but the whole point in creating this repo is to reduce the install size of something like OSGeo Live. Installing all those, including stuff that has to some extent been superceded, seems like it could do more harm than good. 

Looking for more `geopkgs` tho - see here: https://github.com/Robinlovelace/install-gis-ubuntu/blob/master/install-gis.sh#L97
