### ISSUE TITLE
geopandas not working

### ISSUE THREAD

**Issue by Robinlovelace** [Robinlovelace/install-geocomp-ubuntu#4]
Installed the stack but getting this error when trying to load geopandas:

``` python
import geopandas as gpd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```

Based on this: http://darribas.org/gds_scipy16/ipynb_md/06_points.html

Any ideas @darribas ?

**Comment by Robinlovelace** [comment]
Also note it says "ImportError: No module named pandas" when I do, from a shell:

```
$ python
>>> import pandas as pd
```

Was pandas defo installed as part of the PR?

Am I in the right version of Python?

**Comment by darribas** [comment]
have you activated the environment?

```
$ source activate gds
(gds) $ ipython
```

Then try to import them.

**Comment by Robinlovelace** [comment]
```
➜  repos source activate gds               
source: no such file or directory: activate
```

**Comment by darribas** [comment]
Mmm... that suggests `conda` is either not installed or not properly linked to the path. That's supposed to happen with the line:

```
export PATH=`pwd`/miniconda/bin:$PATH
```

Can you check the `miniconda/bin` folder is linked?

**Comment by Robinlovelace** [comment]
OK it now says

```
bash: activate: no such file or directory
```

**Comment by Robinlovelace** [comment]
Seems it didn't get linked - not even sure if it's installed - it pulled down loads of python libs on executing the latest version though.

**Comment by Robinlovelace** [comment]
When running

```
./miniconda.sh -b -p ./miniconda
```

I get:

```
./miniconda.sh: line 290: /home/robin/repos/gds_env/miniconda/pkgs/python-2.7.12-1/bin/python: cannot execute binary file: Exec format error
ERROR:
ERROR:
cannot execute native osx-64 binary, output from 'uname -a' is:
Linux robin-ThinkPad-X230 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by Robinlovelace** [comment]
Plus I think you should `cd` back to to `../` the original working directory at the end - I end up in `gds_env`

**Comment by Robinlovelace** [comment]
But yes double checked and that's defo the problem - imagine it should be a quick fix + PR :+1:

**Comment by Robinlovelace** [comment]
This is the full error message btw:

```
cannot execute native osx-64 binary, output from 'uname -a' is:
Linux robin-ThinkPad-X230 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by darribas** [comment]
Whoops... looks like I copied the wrong link to miniconda... Will fix.

**Comment by darribas** [comment]
That should do it!

**Comment by darribas** [comment]
Any luck @Robinlovelace ? To uninstall the macOS version first, just remove the `miniconda` folder.

**Comment by Robinlovelace** [comment]
Yes - seems to have installed the python stack successfully, great stuff. Next challenge: how to use it? As before `source activate gds` from the bash and `import pandas` from the Python command lines both fail...

**Comment by darribas** [comment]
You still can't `source activate gds`? Did you run the whole chunk of code after replacing the `miniconda` link? These are the steps:
- Remove the `miniconda` folder to be sure.
- Run the line that installs `miniconda` (the updated one with the proper linux link).
- Create the `gds` environment (`conda-env create -f install_gds_stack.yml`).
- Activate it and say hi to a brand new world...

**Comment by Robinlovelace** [comment]
Seems to work now : )

Do you have a recommended IDE with which to interact with this whole new world?

**Comment by Robinlovelace** [comment]
P.s. I think you need to say 

```
source activate gds_test
```

not

```
source activate gds
```

**Comment by darribas** [comment]
@Robinlovelace right, my bad! The environment created is `gds_test`, you're right. In terms of IDE, I write serious code in Vim and everything else on the [Notebook](http://jupyter.org/). My [course](http://darribas.org/gds16/) is all in notebooks, for example.

**Comment by Robinlovelace** [comment]
Well with this install you can be using [nvim](https://github.com/neovim/neovim) instead! 

Yes I played with the notebook - seems good enough, just a little alien but sure you'd get used to it.

Next issue: create a travis test suite, ask others to test it (e.g. to students :) and then promote if it goes down well. Just realised, we've accidentally created the foundation for making our 'R vs Python' dream a reality - all we need to do is upload some data and away we go. Got a good case study here - reckon Python can handle some of that?

https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/vspd-base-shiny.md

Great stuff in any case.

**Comment by darribas** [comment]
yeah! was actually looking at neovim the other day. Looks good.

The environment is actually currently being tested on Linux, macOS and Windows (see the badges [here](https://github.com/darribas/gds_env)).

Regarding the R Vs Python, we're slowly working towards it I think :) It sounds like a small grant for education or code sustainability would be a good fit for the idea?

**Comment by Robinlovelace** [comment]
+1 from me, I'm 100% in on that idea.
